#!/usr/bin/env bash
# bash script to transfer files
if [ "$#" -eq 4 ]; then
        scp  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:$1";
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi
