#!/usr/bin/env bash
# Configure Nginx with custom 404 page

# Install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create a custom 404 HTML page
echo "Ceci n'est pas une page

" | sudo tee /usr/share/nginx/html/404.html > /dev/null


sudo sed -i "/listen 80 default_server;/a error_page 404 /404.html;\nlocation = /404.html {\n    root /usr/share/nginx/html;\n    internal;\n}" /etc/nginx/sites-enabled/default

# Test and restart Nginx
sudo nginx -t && sudo service nginx restart
