#!/usr/bin/env bash

# Configuration script for setting up Nginx on Ubuntu

sudo apt-get -y update
sudo apt-get -y install nginx

# Header
HOST_NAME=$(hostname)
HEADER="\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sudo sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Create a first index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the Nginx configuration file a redirection to another page
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STRING="\n\tlocation /redirect_me {\n\t\t return 301 https://kalaiibsi.com;\n\t}\n"
if [[ -z $FIND ]]; then
    sudo sed -i "42i $STRING" /etc/nginx/sites-available/default
fi

# Add to the Nginx configuration file an error page for 404
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sudo sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

# Restart Nginx service to apply changes
sudo service nginx restart