#!/usr/bin/env bash
# Configures 

# Update the packages
sudo apt-get update
sudo apt-get install software-properties-common -y

sudo add-apt-repository ppa:vbernat/haproxy-1.7 -y
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy=1.7.* -y

# Configure HAProxy
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server  03-web-01 54.174.112.37:80 check
        server  03-web-02 54.237.40.66:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Start and enable the HAProxy service
sudo systemctl start haproxy
sudo systemctl enable haproxy
