#!/usr/bin/env bash
# full manage process

if [ "$1" == "start" ]; then
    ./manage_my_process &  # Start the process in the background
    echo $! | sudo tee /var/run/my_process.pid  # Store the process ID in the pid file
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    kill "$(cat /var/run/my_process.pid)"
    sudo rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    kill "$(cat /var/run/my_process.pid)"
    sudo rm -f /var/run/my_process.pid
    ./manage_my_process &  # Start the process in the background
    echo $! | sudo tee /var/run/my_process.pid  # Store the process ID in the pid file
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
