#!/usr/bin/env bash
#reads content
if [ -e "/etc/passwd" ]; then
    while IFS=: read -r username _ uid _ _ home _; do
        echo "$username:$uid:$home"
    done < "/etc/passwd"
else
    echo "/etc/passwd file does not exist."
fi
