#!/usr/bin/env bash
#reads content

if [ -e "/etc/passwd" ]; then
    awk -F: '{print "Username: " $1, "User ID: " $3, "Home Directory: " $6}' /etc/passwd
else
    echo "/etc/passwd file does not exist."
fi