#!/usr/bin/env bash
# format
if [ -e "apache-access.log" ]; then
    # Use awk to group by IP and HTTP status code, count occurrences, and format the output
    awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
else
    echo "apache-access.log file does not exist."
fi
