#!/usr/bin/env bash
# school file info
file_path="./school"

if [ -e "$file_path" ]; then
    echo "school file exists"

    if [ -f "$file_path" ]; then
	echo "school is a regular file"
    fi
    if [ -s "$file_path" ]; then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

else
    echo "school file does not exist"
fi
